'use strict'

// Materialising the code of bun-inline jobs.

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')

const {
  inlineScriptPath,
  writeInlineScript,
  pruneInlineScripts,
} = require('../src/runner/inline')

async function workspace(t) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'rota-inline-'))
  t.after(() => fs.rm(dir, { recursive: true, force: true }))
  return { inlineDir: path.join(dir, 'inline') }
}

const job = (code, id = 'demo') => ({ id, runner: { type: 'bun-inline', code } })

test('the path produced is deterministic: the interface shows it', () => {
  const paths = { inlineDir: '/tmp/inline' }
  assert.equal(inlineScriptPath(paths, 'ma-job'), '/tmp/inline/ma-job.js')
})

test('the code is written as it is, and the file created if it is missing', async (t) => {
  const paths = await workspace(t)

  const file = await writeInlineScript(paths, job('console.log("bonjour")'))

  assert.equal(file, inlineScriptPath(paths, 'demo'))
  assert.match(await fs.readFile(file, 'utf8'), /^console\.log\("bonjour"\)\n/)
})

// This is the reason for the banner at the foot of the file: a stack trace must
// point at the same line as the one shown in the editor.
test('the code starts on the first line, with no offset', async (t) => {
  const paths = await workspace(t)
  const code = ['const a = 1', 'const b = 2', 'throw new Error("ici")'].join('\n')

  const file = await writeInlineScript(paths, job(code))

  const lines = (await fs.readFile(file, 'utf8')).split('\n')
  assert.equal(lines[0], 'const a = 1')
  assert.equal(lines[2], 'throw new Error("ici")', 'la ligne 3 du code est la ligne 3 du file')
})

test('the file carries a banner saying it is generated', async (t) => {
  const paths = await workspace(t)

  const file = await writeInlineScript(paths, job('const x = 1'))

  const content = await fs.readFile(file, 'utf8')
  assert.match(content, /generated by Rota/)
  assert.match(content, /jobs\/demo\.json/)
  assert.match(content, /any change made here is lost/)
})

test('rewriting replaces the previous version entirely', async (t) => {
  const paths = await workspace(t)

  await writeInlineScript(paths, job('const version = 1'))
  const file = await writeInlineScript(paths, job('const version = 2'))

  const content = await fs.readFile(file, 'utf8')
  assert.match(content, /version = 2/)
  assert.ok(!content.includes('version = 1'), 'no residue of the previous version')
})

test('no temporary file is left behind', async (t) => {
  const paths = await workspace(t)

  await writeInlineScript(paths, job('const x = 1'))

  assert.deepEqual(await fs.readdir(paths.inlineDir), ['demo.js'])
})

test('the sweep removes the jobs that are gone and keeps the others', async (t) => {
  const paths = await workspace(t)
  await writeInlineScript(paths, job('const x = 1', 'garde'))
  await writeInlineScript(paths, job('const x = 2', 'oubliee'))

  await pruneInlineScripts(paths, ['garde'])

  assert.deepEqual(await fs.readdir(paths.inlineDir), ['garde.js'])
})

test('sweeping a directory that is not there does not throw', async (t) => {
  const paths = await workspace(t)
  await assert.doesNotReject(() => pruneInlineScripts(paths, ['peu-importe']))
})
