'use strict'

// Materialising the code of bun-inline jobs.
//
// A bun-inline job carries its code in its JSON. Bun could run it passed as an
// argument (`bun -e`), but the command line has a bounded size and stack traces
// there point at "[eval]" rather than a file. So it is written to disk before
// every execution: the launch path becomes exactly that of an ordinary script —
// same executable, same argument array, no shell string anywhere.
//
// The file is derived content: it is rewritten on every execution from jobs/,
// and deleting it loses nothing.

const { randomUUID } = require('node:crypto')
const fs = require('node:fs/promises')
const path = require('node:path')

// At the top, this banner would offset the line numbers of stack traces relative
// to what the editor shows. It therefore sits at the foot of the file.
const banner = (jobId) =>
  [
    '',
    '// ---',
    `// File generated by Rota from jobs/${jobId}.json.`,
    '// Rewritten before every execution: any change made here is lost.',
    '',
  ].join('\n')

/**
 * Path of the file produced for a job. Deterministic: the interface shows it.
 *
 * `variant` distinguishes the steps of a workflow, which carry its identifier:
 * two bun-inline steps would otherwise write to the same place, and the second
 * would run the first one's code if the two ever crossed.
 */
function inlineScriptPath(paths, jobId, variant = null) {
  return path.join(paths.inlineDir, variant ? `${jobId}.${variant}.js` : `${jobId}.js`)
}

/**
 * Writes the job's code and returns the path of the file.
 *
 * Goes through a temporary file then a rename: two concurrent executions of the
 * same job write the same content, but a reader must never land on a half-written
 * file. The intermediate has a name unique to the call — with the process number
 * alone, two simultaneous writes shared the same one, and the second renamed a
 * file already moved.
 *
 * @param {{inlineDir: string}} paths
 * @param {object} job validated definition, of the bun-inline type
 * @returns {Promise<string>}
 */
async function writeInlineScript(paths, job) {
  const file = inlineScriptPath(paths, job.id, job.inlineVariant ?? null)
  const tmp = `${file}.${randomUUID()}.tmp`

  await fs.mkdir(path.dirname(file), { recursive: true })
  await fs.writeFile(tmp, `${job.runner.code}\n${banner(job.id)}`, 'utf8')
  try {
    await fs.rename(tmp, file)
  } catch (err) {
    await fs.rm(tmp, { force: true })
    throw err
  }

  return file
}

/** Removes the files of jobs that have disappeared, as the history does. */
async function pruneInlineScripts(paths, jobIds) {
  const keep = new Set(jobIds)
  // An identifier contains no dot: what precedes the first one therefore names
  // the job, whether the file is its own or that of one of its steps.
  const owner = (entry) => entry.split('.')[0]

  let entries
  try {
    entries = await fs.readdir(paths.inlineDir)
  } catch {
    return
  }
  for (const entry of entries) {
    if (entry.endsWith('.js') && keep.has(owner(entry))) continue
    // Files of jobs that have disappeared, and intermediates an interrupted
    // write would have left behind.
    if (entry.endsWith('.js') || entry.endsWith('.tmp')) {
      await fs.rm(path.join(paths.inlineDir, entry), { force: true })
    }
  }
}

module.exports = { inlineScriptPath, writeInlineScript, pruneInlineScripts }
